### PR TITLE
RedBlackTree backport review

### PR DESCRIPTION
**Pull request by retronym**
Review of: https://github.com/scala/scala/pull/8749

These optimizations still need to pulled up into type-cases of the inherited methods:

```
[error]  * method --(scala.collection.GenTraversableOnce)scala.collection.immutable.TreeMap in class scala.collection.immutable.TreeMap does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeMap.--")
[error]  * method keySet()scala.collection.immutable.TreeSet in class scala.collection.immutable.TreeMap does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeMap.keySet")
[error]  * method filter(scala.Function1)scala.collection.immutable.TreeMap in class scala.collection.immutable.TreeMap does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeMap.filter")
[error]  * the type hierarchy of class scala.collection.immutable.RedBlackTree#KeysIterator is different in other version. Missing types {scala.collection.AbstractIterator}
[error]    filter with: ProblemFilters.exclude[MissingTypesProblem]("scala.collection.immutable.RedBlackTree$KeysIterator")
[error]  * method tree()scala.collection.immutable.RedBlackTree#Tree in class scala.collection.immutable.TreeSet does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeSet.tree")
[error]  * method ++(scala.collection.GenTraversableOnce)scala.collection.immutable.TreeSet in class scala.collection.immutable.TreeSet does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeSet.++")
[error]  * method --(scala.collection.GenTraversableOnce)scala.collection.immutable.TreeSet in class scala.collection.immutable.TreeSet does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeSet.--")
[error]  * method intersect(scala.collection.GenSet)scala.collection.immutable.TreeSet in class scala.collection.immutable.TreeSet does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeSet.intersect")
[error]  * method diff(scala.collection.GenSet)scala.collection.immutable.TreeSet in class scala.collection.immutable.TreeSet does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeSet.diff")
[error]  * method filter(scala.Function1)scala.collection.immutable.TreeSet in class scala.collection.immutable.TreeSet does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeSet.filter")
```

### CODE REVIEW

**Comment by mkeskells** [comment]
[error]  * method tree()scala.collection.immutable.RedBlackTree#Tree in class scala.collection.immutable.TreeSet does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeSet.tree")

before it was 
`final class TreeMap[A, +B] private (_tree: RB.Tree[A, B])(...
  private[immutable] val tree: RB.Tree[A, B] = _tree
`

now it is 
`final class TreeSet[A] private[immutable] (private[immutable] val tree: RB.Tree[A, Any])(`

`RB` in now `NewRedBlackTree`. I would have thought that this is acceptable. Please confirm

**Comment by mkeskells** [comment]
```
[error]  * method filter(scala.Function1)scala.collection.immutable.TreeMap in class scala.collection.immutable.TreeMap does not have a correspondent in other version
[error]    filter with: ProblemFilters.exclude[DirectMissingMethodProblem]("scala.collection.immutable.TreeSet.filter")
```
It looks like 2.13 is overriding `filter`, when it should be `filterImpl`
I will adjust, but I thing this should be applied to 2.13 as well

**Comment by dwijnand** [comment]
> does not have a correspondent in other version
> [error] filter with: ProblemFilters.exclude[DirectMissingMethodProblem](%22scala.collection.immutable.TreeSet.tree%22)

That's a bug.  It's meant to be an `IncompatibleResultTypeProblem`.  That was fixed in https://github.com/lightbend/mima/releases/tag/0.6.4 but 2.12.x is lagging.

**Comment by szeiger** [comment]
> before it was
> `final class TreeMap[A, +B] private (_tree: RB.Tree[A, B])(... private[immutable] val tree: RB.Tree[A, B] = _tree `

I don't know where you're looking but I see this in 2.12.x:

```
final class TreeMap[A, +B] private (tree: RB.Tree[A, B])(implicit val ordering: Ordering[A])
```

**Comment by szeiger** [comment]
> It looks like 2.13 is overriding `filter`, when it should be `filterImpl`
> I will adjust, but I thing this should be applied to 2.13 as well

I see a few lone `filter` overrides in 2.13. It should be either `filterImpl`, or `filter` plus `filterNot`.

**Pull request closed without merging**
