### PR TITLE
adapt optimizer tests to nuke-impl-classes

### PR DESCRIPTION
**Pull request by lrytz**

### CODE REVIEW

**Comment by lrytz** [comment]
After this all JUnit tests pass **except** `BTypesFromClassfileTest.compareClassBTypes`. This test creates ClassBTypes for a given class in two ways: once by reading data from the symbol, the second time by parsing the classfile and the InlineInfo classfile attribute.

I haven't managed to find out yet why it fails. What differs is the list of implemented interfaces. For example, for `scala/collection/AbstractTraversable`
  - type read from symbol: `List(Lscala/collection/Traversable;)`
  - type read from the classfile: `List(Lscala/collection/Traversable;, Lscala/collection/generic/GenericTraversableTemplate;, Lscala/collection/TraversableLike;, Lscala/collection/Parallelizable;, Lscala/collection/TraversableOnce;, Lscala/collection/GenTraversable;)`

If I look in the bytecode I see yet another thing:
```
public abstract interface scala/collection/Traversable implements scala/collection/TraversableLike scala/collection/GenTraversable  {
```

I'm fine if you disable this test for M4.

**Comment by lrytz** [comment]
I don't have more time to look into this right now, unfortunately.. Leaving for :ski: tomorrow.

There's quite a bit of code that can be removed in the backend (everything dealing with `rewriteFinalTraitMethodInvocations`, whose invocation has been commented out in this PR).

I think for M4 we can just leave it in, I'm happy to clean it up later.

**Comment by retronym** [comment]
@lrytz One big hack in this branch is that I've had to add redundantly add some transitively implemented interfaces to come classes in order to open up access for `invokespecial`. This is done at the last moment in the backend, and is't reflected in the generic signatures nor in the `Symbol`'s info.

**Comment by lrytz** [comment]
Ah, that explains it. I guess this should be cleaned up, i.e., implemented at an earlier stage?

Note that what I pasted as "If I look in the bytecode I see yet another thing" was the actual interfaces in the classfile, not the generic signature.

**Comment by lrytz** [comment]
@retronym I pushed a fix here for https://github.com/scala/scala-dev/issues/86, so all of the inliner works with the new trait encoding.

**Pull request closed without merging**
